# Generated by Django 3.2.18 on 2023-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/images/download_tz65dv', upload_to='Project 5 API/'),
        ),
    ]
